/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ManagerInterface extends utils.Interface {
  functions: {
    "addMember(address,address,address)": FunctionFragment;
    "isMember(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addMember" | "isMember"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;

  events: {};
}

export interface Manager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addMember(
      _nft: string,
      _checker: string,
      _member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isMember(
      _nft: string,
      _member: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { result: boolean }>;
  };

  addMember(
    _nft: string,
    _checker: string,
    _member: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isMember(
    _nft: string,
    _member: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    addMember(
      _nft: string,
      _checker: string,
      _member: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isMember(
      _nft: string,
      _member: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addMember(
      _nft: string,
      _checker: string,
      _member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isMember(
      _nft: string,
      _member: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addMember(
      _nft: string,
      _checker: string,
      _member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isMember(
      _nft: string,
      _member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
